[build]
  command = "npm run build"
  publish = "dist"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy para el backend local en desarrollo
[[dev]]
  functions = "netlify/functions"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = true
