[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

# Redirección de llamadas API hacia el backend en AWS
[[redirects]]
  from = "/backend-api/*"
  to = "http://18.119.167.171:3001/api/:splat"
  status = 200
  force = true

# ⚠️ Elimina redirección de dominio HTTP → HTTPS aquí
# Netlify ya fuerza HTTPS por defecto, y no es necesario este bloque:
# [[redirects]]
#   from = "http://demodba2.netlify.app/*"
#   to = "https://demodba2.netlify.app/:splat"
#   status = 301
#   force = true

# Redirección para SPA (Vue, React, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
