[build]
  base = "frontend"  # Especifica que todo se ejecuta desde esta carpeta
  publish = "dist"   # Directorio de compilación dentro de frontend
  command = "npm run build"

[[redirects]]
  from = "/backend-api/*"
  to = "http://18.119.167.171:3001/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirección HTTPS obligatoria
[[redirects]]
  from = "http://demodba2.netlify.app/*"
  to = "https://demodba2.netlify.app/:splat"
  status = 301
  force = true

# Regla para Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200