[build]
  command = "npm run build"
  publish = "dist"

# Configuración para Vue Router (modo history)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración básica de caché (opcional)
[build.caching]
  enabled = true

# Variables de entorno (reemplaza con tus valores)
#[build.environment]
#  VUE_APP_API_URL = "https://tu-api.com"
#  VUE_APP_ENV = "production"