[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/backend-api/*"
  to = "http://18.119.167.171:3001/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirección HTTPS universal
[[redirects]]
  from = "http://demodba2.netlify.app/*"
  to = "https://demodba2.netlify.app/:splat"
  status = 301
  force = true